[FEAT/#1] 1주차 필수 과제
AND-SOPT-ANDROID/hyobeen-park pull request #3
Opened 2024-10-10 12:47 UTC by Hyobeen-Park

## Related issue 🛠
- closed #1

## Work Description ✏️
- [x] 회원가입
- [x] 로그인
- [x] 마이페이지

## Screenshot 📸
<img src="" width="360"/>

https://github.com/user-attachments/assets/84132222-34c7-4fa4-98c3-bd5f3ba46c95

## Uncompleted Tasks 😅
- [ ] 스낵바...

## To Reviewers 📢
스낵바를 SnackbarHost 이용해서 해보고 싶었는데 계속 안뜨더라구요😅 그래서 일단 토스트로 구현했는데 원인 알아내면 스낵바로 수정할게요..!!

2024-10-10 14:44 UTC, boiledEgg-s commented
터닝 화이팅~

2024-10-10 14:55 UTC, leeeyubin reviewed
터닝 화이팅~💚☘️

2024-10-12 10:58 UTC, l2hyunwoo commented
안녕하세요. 명예 OB 리뷰어 이현우입니다. 앞으로 N번의 과제동안 잘 부탁드리겠습니다. 🙇🏻 

해당 PR의 리뷰는 금잔디조 내 모든 분들의 리뷰가 완료된 후 작성하도록 하겠습니다.

2024-10-12 20:35 UTC, MinseoSONG reviewed
역시 오비 .. 코드가 엄청 알차요 ! 참고하고 갑니다 ~ !

2024-10-12 20:35 UTC, MinseoSONG commented on app/src/main/java/org/sopt/and/core/designsystem/component/SocialLoginButton.kt
> +    }
우와 2주차 내용인 LazyRow를 먼저 쓰셨었네요 .. !
근데 그냥 Row가 아닌 LazyRow를 쓰신 이유가 있으실까요 ?? 여기서는 단순히 딱 이미지 4개만 띄운다고 생각해서 Row를 써도 괜찮지 않나 싶어서요 !

2024-10-12 20:35 UTC, MinseoSONG commented on app/src/main/java/org/sopt/and/feature/signin/SignInActivity.kt
> +
이거 따로 저장해두고 쓰는게 더 좋은가요 ?? 저는 바로 해버려성

2024-10-12 20:35 UTC, MinseoSONG commented on app/src/main/java/org/sopt/and/feature/signin/SignInActivity.kt
> +                        },
Scaffold에서 snackbar를 설정할 수 있군요 .. ? 새로운 사실 !

2024-10-12 20:35 UTC, MinseoSONG commented on app/src/main/java/org/sopt/and/feature/signin/SignInScreen.kt
> +        viewModel.signInSideEffect.flowWithLifecycle(lifecycle = lifecycleOwner.lifecycle)
우와 viewmodel에 lifecycle까지 다 처리하셨네요 최고 ㅠ 0 ㅠ

2024-10-12 20:35 UTC, MinseoSONG commented on app/src/main/java/org/sopt/and/feature/signin/SignInScreen.kt
> +}
정해지지않은 것들을 TODO로 해놓는군요 .. 배워갑니다 !

2024-10-12 20:35 UTC, MinseoSONG commented on app/src/main/java/org/sopt/and/feature/signup/SignUpViewModel.kt
> +    }
와 조건을 따로 이렇게 정해놨네요 ,, 생각도 못한 방법

2024-10-13 02:07 UTC, beom84 approved these changes
잘봤습니다 .. LauncheEffect에 대해서 다음에 깊은 얘기를 해주세요

2024-10-13 02:07 UTC, beom84 commented on app/src/main/java/org/sopt/and/WavveApplication.kt
여기서 hilt를 사용하신 이유는 무엇인가요?

2024-10-13 02:07 UTC, beom84 commented on app/src/main/java/org/sopt/and/core/designsystem/component/SocialLoginButton.kt
> +        LazyRow(
LazyRow를 넣은 이유가 따로 있나요?

2024-10-13 02:07 UTC, beom84 commented on app/src/main/java/org/sopt/and/core/designsystem/component/textfield/EmailextField.kt
> +    email: MutableState<String>,
MutableState를 사용하는 이유가 있나요?

2024-10-13 02:07 UTC, beom84 commented on app/src/main/java/org/sopt/and/core/extension/ContextExt.kt
extention은 어떤 걸 넣는 package인가요?

2024-10-13 02:07 UTC, beom84 commented on app/src/main/java/org/sopt/and/feature/mypage/component/MyPageContent.kt
component를 분리할때 재사용성이 높은 component만 따로 빼놓으시는건가요?

2024-10-13 02:07 UTC, beom84 commented on app/src/main/java/org/sopt/and/feature/signup/SignUpScreen.kt
> +    LaunchedEffect(viewModel.signUpSideEffect, lifecycleOwner) {
Toast , navigate를 이용할때는 launchedeffect를 사용하는것이 효율적인가요?

2024-10-13 02:07 UTC, beom84 commented on app/src/main/res/values/strings.xml
> +    <string name="sign_up_title_only">만으로</string>
재사용가능하도록 끊어서 만드시는군요.. 메모메모

2024-10-13 02:37 UTC, beom84 commented on app/src/main/java/org/sopt/and/feature/mypage/MyPageActivity.kt
> +fun MyPageScreen(
간단한 screen 구현이기때문에 따로 안빼놓은건가요?

2024-10-13 02:40 UTC, beom84 commented on app/src/main/java/org/sopt/and/feature/signin/SignInActivity.kt
> +    private fun isSignInAvailable(email: String, password: String): Boolean {
이런식으로 할수 잇군요 메모하겠습니다..

2024-10-13 02:50 UTC, beom84 approved these changes
2회독하기

2024-10-13 02:50 UTC, beom84 commented on app/src/main/java/org/sopt/and/feature/signin/SignInScreen.kt
> +fun SignInRoute(
Route의 역할은 정확히 무엇인가요?

2024-10-13 02:50 UTC, beom84 commented on app/src/main/java/org/sopt/and/feature/signin/SignInScreen.kt
> +            Box(
왜 Box를 사용한건가요?

2024-10-13 02:50 UTC, beom84 commented on app/src/main/java/org/sopt/and/feature/signin/SignInViewModel.kt
> +    val signInSideEffect get() = _signInSideEffect.asSharedFlow()
어떻게 굴러가는지 다음에 설명 부탁드려도 될까요!

2024-10-13 02:50 UTC, beom84 commented on app/src/main/java/org/sopt/and/feature/signup/SignUpScreen.kt
> +private fun SignUpTitle(
이런식으로 하면 되는군요! 배워갑니다

2024-10-13 06:48 UTC, wjdrjs00 reviewed
1주차 고생하셨습니다!! 너무 잘하십니다...!
(추가로 여러 파일에서 end of line 문구가 보입니다! https://www.aleksandrhovhannisyan.com/blog/crlf-vs-lf-normalizing-line-endings-in-git/
https://stackoverflow.com/questions/24093609/how-can-i-configure-android-studio-to-add-new-line-at-end-of-file
이 링크 참고하면 발생이유와 해결방법 참고할 수 있습니다! 저도 이번기회에 다시 공부했어요!)

2024-10-13 06:48 UTC, wjdrjs00 commented on app/src/main/res/values/strings.xml
string 추출방식 배워갑니다!!

2024-10-13 06:48 UTC, wjdrjs00 commented on app/src/main/java/org/sopt/and/core/designsystem/component/SocialLoginButton.kt
> +)
list 활용해서 이미지 처리하는 방법 배워갑니다!! (하나씩 할뻔..ㅎ)

2024-10-13 06:48 UTC, wjdrjs00 commented on app/src/main/java/org/sopt/and/core/designsystem/component/SocialLoginButton.kt
> +    }
저도 궁금

2024-10-13 06:48 UTC, wjdrjs00 commented on app/src/main/java/org/sopt/and/core/designsystem/component/textfield/EmailextField.kt
> +    email: MutableState<String>,
저도 궁금!

2024-10-13 06:48 UTC, wjdrjs00 commented on app/src/main/java/org/sopt/and/core/designsystem/component/topappbar/CloseButtonTopAppBar.kt
전 BackButtonTopAppBar이랑 CloseButtonTopAppBar 합쳐서 하나의 탑바로 만드는 방식을 생각했는데, 생각해보니 이렇게 따로 만드는 방법도 나중에 앱 확장성측면에서 더 유리할거 같네용!

2024-10-13 06:48 UTC, wjdrjs00 commented on app/src/main/java/org/sopt/and/core/extension/ContextExt.kt
제 생각에는 확장함수를 관리하는 패키지로 사용한거 같습니다!
+ context에 toast를 확장함수로 사용한 방법 배워갑니다! 이런식으로 구현 가능하군요!

2024-10-13 06:48 UTC, wjdrjs00 commented on app/src/main/java/org/sopt/and/feature/mypage/MyPageActivity.kt
> +            )
커스텀 컴포넌트 활용하니 확실히 보기 편안합니다! 저도 다음 미션부터 적용해보겠습니다!

2024-10-13 06:48 UTC, wjdrjs00 commented on app/src/main/java/org/sopt/and/feature/signin/SignInActivity.kt
> +                                coroutine.launch {
코루틴,, (이 코드에서 어떤 역할을 하는지 궁금합니다!!)

2024-10-13 06:48 UTC, wjdrjs00 commented on app/src/main/java/org/sopt/and/feature/signin/SignInActivity.kt
> +    private fun isSignInAvailable(email: String, password: String): Boolean {
저도 메모합니다..

2024-10-13 06:48 UTC, wjdrjs00 commented on app/src/main/java/org/sopt/and/feature/signin/SignInScreen.kt
> +    val lifecycleOwner = LocalLifecycleOwner.current
어떤역할을 하는지 궁금합니다!!

2024-10-13 06:48 UTC, wjdrjs00 commented on app/src/main/java/org/sopt/and/feature/signin/SignInScreen.kt
> +        onSignUpButtonClick = viewModel::onSignUpButtonClick,
:: 은 어떤 기능을 하는지 궁금합니다!

2024-10-13 06:48 UTC, wjdrjs00 commented on app/src/main/java/org/sopt/and/feature/signin/SignInScreen.kt
> +            onSignInButtonClick = TODO(),
호오 TODO() 활용하는거 배워갑니다!

2024-10-13 06:48 UTC, wjdrjs00 commented on app/src/main/java/org/sopt/and/feature/signup/SignUpScreen.kt
> +    LaunchedEffect(viewModel.signUpSideEffect, lifecycleOwner) {
저도 궁금합니다!
(화면이 전환되면서 유저와의 상호작용과 관련없이 동작해야 하기 때문인가요??)

2024-10-13 06:48 UTC, wjdrjs00 commented on app/src/main/java/org/sopt/and/feature/signup/SignUpViewModel.kt
> +    }
저도 배워갑니다!
+ 제가 알기론 코틀린 컨벤션에서 companion object {}의 위치가 
    첫째 : 프로퍼티(속성)의 선언과 초기화 블록
    둘째 : 보조생성자
    세번째 : 메소드 선언
    네번째 : 동반객체 (Companion Object)
이렇게 따르는 걸로 알고있습니다!

2024-10-13 06:48 UTC, wjdrjs00 commented on app/src/main/java/org/sopt/and/feature/signin/SignInViewModel.kt
> +    val signInSideEffect get() = _signInSideEffect.asSharedFlow()
저도 부탁드립니다!

2024-10-13 09:18 UTC, l2hyunwoo requested changes
안녕하세요! 안드로이드 명예 오비 이현우입니다.

효빈님 컴포즈를 잘 활용하시는군요! 이전 앱잼에서 컴포즈를 활용하신만큼 컴포즈 사용에서 조금 깊은 곳까지 리뷰를 남겨드렸습니다. 한번 고민해보시고 차근차근 답해보신다면 컴포즈를 대하는 것에 더 편해질 수 있을 것 같아요.

상태관리를 설계하는 쪽에서 많은 고민을 하신 것 같아요. 한 주동안 천천히 생각해보시는 것을 추천드립니다. 저는 처음에 공부할 때 노트로 상태관리 부분을 그려가면서 정리를 많이한 것 같아요. 아무튼 고생많으셨습니다. 2주차 과제 전까지 수정사항 반영해주신다면 추가 리뷰 달겠습니다.

2024-10-13 09:18 UTC, l2hyunwoo commented on gradle/libs.versions.toml
> +hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
`hilt-core`와 `hilt-android`를 app module에서 다 의존성에 추가하셨는데, 그런 이유가 있을까요? `hilt-core`와 `hilt-android`의 어떤 차이가 있을까요?

2024-10-13 09:18 UTC, l2hyunwoo commented on gradle/libs.versions.toml
> +hilt-manager = {group = "androidx.hilt" , name = "hilt-compiler", version.ref = "hiltManager"}
hiltManager라는 변수명에 어떤 의미를 담아두신게 있을까요?

2024-10-13 09:18 UTC, l2hyunwoo commented on build.gradle.kts
> +    alias(libs.plugins.ksp) apply false
Q) `apply false`의 의미를 알고 계실까요? 왜 적용하셨나요?

2024-10-13 09:18 UTC, l2hyunwoo commented on app/src/main/res/values/strings.xml
> +    <string name="sign_up_title_only">만으로</string>
```suggestion
    <string name="sign_up_title_only">%s만으로</string>
```

이렇게 사용하시면

```
  val title = stringResource(R.string. sign_up_title_only, "회원가입 없이 인증")
```

이런식으로도 사용가능하답니다!

2024-10-13 09:18 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/and/feature/signup/SignUpViewModel.kt
> +        }
Q) update와 value에 값을 넣는 것에 차이점은 무엇일까요?

2024-10-13 09:18 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/and/feature/signup/SignUpViewModel.kt
> +    }
여기서 요구사항을 바꾼다고 생각을 해볼게요.

> - 사용자가 어떤 부분에서 조건을 충족 못했는지 알아야 한다

이런 경우에는 어떻게 구현을 변경해야할까요?

2024-10-13 09:18 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/and/feature/signup/SignUpViewModel.kt
> +
여기 빈줄!

2024-10-13 09:18 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/and/feature/signup/SignUpScreen.kt
> +    LaunchedEffect(viewModel.signUpSideEffect, lifecycleOwner) {
@beom84 @wjdrjs00 화면의 이동이 UI에 그려지는 상태와 연관이 있는지 생각해보시면 좋을 것 같습니다!

2024-10-13 09:18 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/and/feature/signup/SignUpScreen.kt
> +    val signUpState by viewModel.signUpState.collectAsState()
```suggestion
    val signUpState by viewModel.signUpState.collectAsStateWithLifecycle()
```

생명주기 안정적으로 state 받아와서 사용하는 것을 권장합니다.

2024-10-13 09:18 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/and/feature/signup/SignUpScreen.kt
> +    val password = remember { mutableStateOf("") }
1)

```suggestion
    var email by remember { mutableStateOf("") }
    var password by remember { mutableStateOf("") }
```

이렇게 선언하시면 하단에서 email 변수를 사용해서 state를 변경하실 수 있어요.

2)

ViewModel에서도 상태를 관리하고 여기서도 email, pw 상태관리를 하시네요. 중복된 상태관리는 상태 불일치의 가능성을 높이기 때문에 최대한 상태관리는 한 곳에서 이뤄져야합니다. 

그에 대한 증빙으로

```kotlin
@Composable
fun SignUpScreen(
    onSignUpButtonClick: (String, String) -> Unit,
    onIdChange: (String) -> Unit,
    onPasswordChange: (String) -> Unit,
    modifier: Modifier = Modifier,
) {
```

지금 뷰모델에 있는 상태관리를 위해 이렇게 패러미터들을 받아오고 계신데 로컬 변수에서 `mutableStateOf`를 사용하신 것이라면 패러미터에 있는 `onIdChange`를 사용하지 말고 email의 프로퍼티를 변경해야하지 않을까요?

생각이 너무 많이 들어가있는 코드인 것 같습니다. 어떤 상태들을 주로 변경해야하는지 생각해보시면 좋을 것 같아요.

2024-10-13 09:18 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/and/feature/signup/SignUpScreen.kt
> +            onPasswordChange = TODO()
이러면 preview가 동작하나요? (단순 궁금증)

```suggestion
            onSignUpButtonClick = {},
            modifier = {},
            onIdChange = {},
            onPasswordChange = {},
```

(패러미터 두개 이상 있으면 {_, _ -> } 이렇게 해야하지만) 이렇게 하는게 보는 입장에서 좀 더 안정적일 것 같습니다.

2024-10-13 09:18 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/and/feature/signup/SignUpScreen.kt
> +    val isPasswordVisible = remember { mutableStateOf(false) }
이건 로컬에서 상태관리해도 좋을 것 같네요! 좋은 판단입니다.

2024-10-13 09:18 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/and/feature/signin/SignInActivity.kt
> +        }
registerForActivityResult도`rememberLauncherForActivityResult`라는 좋은 컴포저블 함수를 사용할 수 있습니다. 컴포즈 내에서 사용해보시는 것을 추천드려요!

2024-10-13 09:18 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/and/feature/signin/SignInActivity.kt
> +                userId = result.data?.getStringExtra(ID_KEY) ?: ""
```suggestion
                userId = result.data?.getStringExtra(ID_KEY).orEmpty()
```

이렇게도 쓸 수 있습니다. 그런데 이건 넘모나 취향차이

2024-10-13 09:18 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/and/feature/signin/SignInActivity.kt
> +    private var userPassword: String = ""
- state로 받지 않아서 변경되어도 리컴포지션에 직접적인 영향을 주지 않습니다.
- 액티비티 재생성시에(테마 변경/글씨체 변경 etc) 이 변수들은 어떻게 될까요?

2024-10-13 09:18 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/and/feature/signin/SignInActivity.kt
> +    private fun isSignInAvailable(email: String, password: String): Boolean {
이거 뷰모델에도 있는데 여기에서도 필요한 이유가 있을까요?

2024-10-13 09:18 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/and/feature/signin/SignInScreen.kt
> +    viewModel: SignInViewModel = hiltViewModel(),
`hiltViewModel()`과 `viewModel()`의 차이는 무엇일까요?

2024-10-13 09:18 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/and/feature/signin/SignInActivity.kt
> +                        )
사실 navigationIcon의 기본성격이 BackButton이긴 해서ㅋㅋ 굳이 `BackButtonTopAppBar`라고 안해도 괜찮을 것 같아요.

spec - https://m3.material.io/components/top-app-bar/specs

2024-10-13 09:18 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/and/feature/mypage/component/MyPageTextButton.kt
> +fun MyPageTextButton(
[이런 Composable](https://developer.android.com/develop/ui/compose/components/button#text_button)도 있답니다.

2024-10-13 09:18 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/and/feature/mypage/component/MyPageTextButton.kt
> +        Row {
Icon이나 Text사이즈가 불일치할 때 한쪽이 밑으로 내려가 보이는 현상이 있을 수 있거든요?

그래서 Row의 verticalAlignment에 Alignment.centerVertically 속성 주는 것도 좋습니다.

2024-10-13 09:18 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/and/feature/mypage/component/MyPageContent.kt
> +            tint = Color.Gray,
👍🏻

2024-10-13 09:18 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/and/core/designsystem/component/topappbar/BackButtonTopAppBar.kt
`BackButtonTopAppBar`, `CloseButtonTopAppBar` 두벌로 만드는게 과연 좋을까요? 만약에 센터 제목 텍스트 속성 변경한다고 했을 때 BackButtonTopAppBar나 CloseButtonTopAppBar 둘 중 하나만 변경하는 실수가 발생할 수 있을 것 같아요.

2024-10-13 09:18 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/and/core/designsystem/component/textfield/PasswordTextField.kt
> +    onValueChange: (String) -> Unit,
password도 (value, onValueChange)로 구성되어있는데 onValueChange라는 콜백을 따로 두는건 불필요한 것 같아요. 만약 둘 다 필요하다고 생각하시면 그건 구조적 결함이라고 생각합니다.

2024-10-13 09:18 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/and/core/designsystem/component/textfield/PasswordTextField.kt
> +        },
```suggestion
        onValueChange = { newValue ->
            password.value = newValue
        },
```

이렇게 줄일 수 있도록 구조 변경이 있어야할 것 같네요.

2024-10-13 09:18 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/and/core/designsystem/component/SocialLoginButton.kt
> +        LazyRow(
모든 아이템이 한번에 화면에 다 보이는 경우에는 그냥 Row 쓰시고 horizontalScroll 쓰는것과 성능상 차이가 없습니다.

2024-10-13 09:18 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/and/core/designsystem/component/SocialLoginButton.kt
> +            }
lazyRow를 쓰는 경우에는 key 함수를 사용하시는 것이 좋습니다. 그 이유를 한번 찾아보시겠어요?

2024-10-13 09:18 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/and/core/designsystem/component/SocialLoginButton.kt
> +            items(4) { image ->
```suggestion
            items(4) { index ->
```

정도로 변경하는게 가독성이 더 좋아질 것 같네요.

2024-10-13 09:18 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/and/WavveApplication.kt
> +}
```suggestion
class WavveApplication : Application()
```

이렇게 줄일 수 있습니다. 필요한 경우에 따로 onCreate 선언해보세요!

2024-10-13 09:18 UTC, l2hyunwoo commented on app/src/main/AndroidManifest.xml
>              android:exported="true"
Q) exported 속성이 true/false에 따라서 어떤 차이가 있는지 아신가요?

2024-10-13 16:05 UTC, wjdrjs00 approved these changes

2024-10-14 08:31 UTC, beom84 commented on app/src/main/java/org/sopt/and/core/extension/ContextExt.kt
고마워요 스피드 웨건!

2024-10-16 00:36 UTC, jihyunniiii reviewed
고생하셨습니다 ~

2024-10-16 00:36 UTC, jihyunniiii commented on app/src/main/java/org/sopt/and/core/designsystem/component/textfield/EmailextField.kt
> +    email: MutableState<String>,
저도 궁금합니다요

2024-10-16 00:36 UTC, jihyunniiii commented on app/src/main/java/org/sopt/and/core/designsystem/component/textfield/EmailextField.kt
> +            onValueChange(newValue)
email.value = newValue를 따로 해주시는 이유가 있나요?
EmailTextField의 Value값이 email이고, 이 값을 onValueChange함수를 통해 변경해주시는 것이 좋을 것 같습니다.

2024-10-16 00:36 UTC, jihyunniiii commented on app/src/main/java/org/sopt/and/core/designsystem/component/textfield/EmailextField.kt
> +            onValueChange(newValue)
혹은 둘 중에 하나의 로직만 사용할 수 있게요

2024-10-16 00:36 UTC, jihyunniiii commented on app/src/main/java/org/sopt/and/core/designsystem/component/textfield/PasswordTextField.kt
EmailTextField와 PasswordTextField 간 유사한 점이 많은 것 같네요!
하나의 Component로 만들거나, BasicComponent를 만들어 확장해서 두 개의 Component를 만드는 방식에 대해서도 고민해보시면 좋을 것 같아요!

2024-10-16 00:36 UTC, jihyunniiii commented on app/src/main/java/org/sopt/and/feature/mypage/MyPageActivity.kt
> +        val email = intent.getStringExtra(ID_KEY) ?: ""
```suggestion
        val email = intent.getStringExtra(ID_KEY).orEmpty()
```
요렇게 적어줄 수도 있습니다.

2024-10-16 00:36 UTC, jihyunniiii commented on app/src/main/java/org/sopt/and/feature/mypage/component/MyPageTextButton.kt
> +fun MyPageTextButton(
ㅎㅓㄹ 신기해요

2024-10-16 00:36 UTC, jihyunniiii commented on app/src/main/java/org/sopt/and/feature/signin/SignInActivity.kt
> +                                coroutine.launch {
<img width="781" alt="스크린샷 2024-10-15 오후 8 25 37" src="https://github.com/user-attachments/assets/d8c5c310-f753-49f8-9cf7-e2ecb8dcf6f6">

showSnackbar 함수의 내부 코드인데요! suspend 함수로 선언된 것을 확인할 수 있습니다.
즉, showSnackbar 함수가 비동기적으로 실행되는 suspend 함수이기 때문에 코루틴 환경에서 호출해야합니다!

2024-10-16 00:36 UTC, jihyunniiii commented on app/src/main/java/org/sopt/and/feature/signin/SignInScreen.kt
> +    val lifecycleOwner = LocalLifecycleOwner.current
현재 컴포저블이 속한 Activity 또는 Fragment의 LifeCycleOwner를 가져오는 역할을 합니다!

2024-10-16 00:36 UTC, jihyunniiii commented on app/src/main/java/org/sopt/and/feature/signin/SignInScreen.kt
> +        onSignUpButtonClick = viewModel::onSignUpButtonClick,
더블콜론이라는 친구인데요! 저희가 Intent를 사용할 때도 MainActivity::class.java <- 이런 식으로 작성했었죠? 여기에 있는 ::과 같은 친구입니다.
주로 함수, 메소드, 클래스 등을 참조할 때 사용해요. (조금 더 자세히 알고 싶으시면 리플렉션에 대해 찾아보시면 좋을 것 같네요 ㅎㅎ)

2024-10-16 14:48 UTC, Hyobeen-Park commented on app/src/main/java/org/sopt/and/core/designsystem/component/SocialLoginButton.kt
> +    }
아주 예리하신데요?!?? 우선 같은 이미지가 4번이나 반복돼서 LazyRow를 사용했는데요!! 지금 생각해보니 Row를 사용하는 것이 좀 더 나을 것 같네요ㅎㅎ

2024-10-16 15:02 UTC, Hyobeen-Park commented on app/src/main/java/org/sopt/and/core/designsystem/component/SocialLoginButton.kt
> +        LazyRow(
과제 할 당시에는 반복되는 뷰 -> LazyRow 라는 흐름으로 단순하게 생각해서 했었는데 지금 생각해보니 항상 한 화면에 보이는 뷰라 Row로만 처리하는게 더 깔끔할 것 같아요!! 다들 아주 예리하시네요ㅎㅎ

2024-10-16 15:12 UTC, Hyobeen-Park commented on app/src/main/java/org/sopt/and/feature/signin/SignInActivity.kt
> +
저는 회원가입 버튼을 누를 때 resultLauncher를 사용하는데 버튼을 누를 때마다 객체를 생성하는 것보다 외부에서 한 번만 만들어두는 것이 더 좋을 것 같아서 이렇게 구현했습니다!!(그치만 정답은 모릅니다요,,,😊)

2024-10-16 15:14 UTC, Hyobeen-Park commented on app/src/main/java/org/sopt/and/feature/signin/SignInActivity.kt
> +                        },
맞아요!! Scaffold에는 snackbarHost도 포함되어 있어서 이렇게 구현이 가능합니다😊추가적으로 topBar, bottomBar, floatingActionButton 도 Scaffold에서 구현이 가능하답니다!

2024-10-16 15:17 UTC, Hyobeen-Park commented on app/src/main/java/org/sopt/and/feature/signup/SignUpViewModel.kt
> +    }
쿄쿄 맞아요!! Companion Object는 마지막에 넣어야 하는데 습관이 돼서 자꾸 까먹네요😅 깔끔한 정리 감사해요!

2024-10-16 15:23 UTC, Hyobeen-Park commented on app/src/main/java/org/sopt/and/WavveApplication.kt
hilt를 사용할 때는 `@HiltAndroidApp` 이라는 어노테이션을 사용해서 Application 클래스를 할당해주어야 해당 어플리케이션이 hilt를 사용한다는 사실을 라이브러리가 인식할 수 있어요!!

2024-10-16 15:26 UTC, Hyobeen-Park commented on app/src/main/java/org/sopt/and/core/designsystem/component/textfield/EmailextField.kt
> +    email: MutableState<String>,
mutableState 로 선언한 변수를 그대로 전달하려고 했던 것 같은데... 이 컴포넌트는 전체적으로 수정이 많이 필요할 것 같네요🤔

2024-10-16 15:27 UTC, Hyobeen-Park commented on app/src/main/java/org/sopt/and/core/extension/ContextExt.kt
캬~ 맞습니다!! 확장함수를 관리하는 패키지로 사용했어요!

2024-10-16 15:28 UTC, Hyobeen-Park commented on app/src/main/java/org/sopt/and/feature/mypage/component/MyPageContent.kt
여러번 반복되는 뷰를 component로 구현했는데요! 그 중에서 MyPage에서만 사용되는 컴포넌트들은 `mypage/component`에 모아두었습니다😊

2024-10-16 15:33 UTC, Hyobeen-Park commented on app/src/main/res/values/strings.xml
> +    <string name="sign_up_title_only">만으로</string>
흠흠 정확히 말하면 텍스트 색을 다르게 지정해야 해서 끊어서 만들었습니다😉

2024-10-16 15:36 UTC, Hyobeen-Park commented on app/src/main/java/org/sopt/and/feature/mypage/MyPageActivity.kt
> +fun MyPageScreen(
네!! 내부 로직이 많지 않고 UI만 보여주면 끝이라 따로 분리하진 않았는데 곧 이친구도 분리될 예정입니다ㅎㅎ

2024-10-16 15:39 UTC, Hyobeen-Park commented on app/src/main/java/org/sopt/and/feature/signin/SignInScreen.kt
> +fun SignInRoute(
이부분은 약간 미래지향적인... 코드였는데요ㅎㅎ 1차 과제에서는 Activity를 사용했지만 추후에 navigation으로 수정해줄 생각이었어서 Route를 사용했습니다. navigation에서 스크린을 식별하는 이름이라고 생각해주시면 될 것 같아요..!!

2024-10-16 15:44 UTC, Hyobeen-Park commented on app/src/main/java/org/sopt/and/feature/signin/SignInScreen.kt
> +            Box(
텍스트 사이에 있는 구분선을 Box로 구현해봤습니다ㅎㅎ 

사실 이런 구분선은 Row / Column을 활용할 수도 있고 Vertical / Horizontal Divider를 사용해서도 구현이 가능합니다. 그리고 Divider가 구분선을 위한 컴포넌트라 저친구를 사용하는게 더 용도에 맞게 사용한 것 같긴 하네요ㅎㅎ

2024-10-16 15:51 UTC, Hyobeen-Park commented on app/src/main/java/org/sopt/and/feature/signin/SignInViewModel.kt
> +    val signInSideEffect get() = _signInSideEffect.asSharedFlow()
sideEffect는 UI 외의 부수적인 효과들(토스트, 스낵바, 화면이동 등)을 처리할 때 사용한다고 한줄 요약 해볼게요..!

https://developer.android.com/develop/ui/compose/side-effects?hl=ko

2024-10-16 15:55 UTC, Hyobeen-Park commented on app/src/main/java/org/sopt/and/feature/signin/SignInActivity.kt
> +                                coroutine.launch {
역시 팟장님..!! 깔꼼한 설명 감사합니다🩷

2024-10-16 15:56 UTC, Hyobeen-Park commented on app/src/main/java/org/sopt/and/feature/signin/SignInScreen.kt
> +    val lifecycleOwner = LocalLifecycleOwner.current
진짜 최고...⭐

2024-10-16 15:59 UTC, Hyobeen-Park commented on app/src/main/java/org/sopt/and/feature/signin/SignInScreen.kt
> +        onSignUpButtonClick = viewModel::onSignUpButtonClick,
와.. 항상 쓰면서 `MainActivity::class.java` 이 친구랑 같은 친구라고는 생각을 못했네요..!! 신기해...

그리고 함수에서 파라미터의 순서가 동일하다면 :: 를 사용할 수 있는데요! 다만 파라미터가 여러개라면 조금 조심하는 것이 좋을 것 같아요!!

2024-10-16 16:14 UTC, Hyobeen-Park commented on gradle/libs.versions.toml
> +hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
사실 라이브러리들은 잘 모르고 추가했었는데...😅 알아보니 `hlit-core` 가 `hlit-android`  에서 android 관련 코드를 제거한 라이브러리라고 하네요!! 테스트 해봤을 때 `hilt-core`가 없어도 프로젝트가 잘 돌아가던데 그럼 `hilt-core`는 없애도 되는걸까요?!?? android에서는 사용할 일이 아예 없는건지 궁금하네요!! 이건 좀 더 알아봐야겠어요😊

2024-10-17 02:37 UTC, l2hyunwoo commented on gradle/libs.versions.toml
> +hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-core는 제거해도 괜찮습니다. 순수 코틀린 모듈이나 테스트 단에서 참조할 때 필요한 라이브러리라 생각하면 좋아요.

2024-10-17 07:54 UTC, Hyobeen-Park commented on gradle/libs.versions.toml
> +hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
아하!!! 설명 감사합니다! 뭔가 hilt 라이브러리와 조금 더 친해진 기분이네요😊

2024-10-17 08:46 UTC, Hyobeen-Park commented on gradle/libs.versions.toml
> +hilt-manager = {group = "androidx.hilt" , name = "hilt-compiler", version.ref = "hiltManager"}
compiler 라이브러리가 여러개라 이름이 겹쳐서 manager 라는 이름을 사용하게 되었는데요..! 라이브러리 정리를 한 번 해야겠네요ㅎㅎ

2024-10-17 10:19 UTC, Hyobeen-Park commented on build.gradle.kts
> +    alias(libs.plugins.ksp) apply false
해당 라이브러리를 프로젝트 전체가 아닌 일부에만 적용하기 위해 `apply false`를 지정하는 것으로 알고 있습니다! 

hilt 는 `apply true` 로 적용을 하지 못하도록 막혀 있는데요 이번에 처음으로 이 이유에 대해 생각해보았는데 hilt는 android에만 적용될 수 있어서 전체 프로젝트에는 적용할 수 없도록 미리 막아둔 것이 아닌가... 하는 생각을 했습니다ㅎㅎ

2024-10-17 10:21 UTC, Hyobeen-Park commented on app/src/main/res/values/strings.xml
> +    <string name="sign_up_title_only">만으로</string>
%s를 사용하는 것도 편해보이네요..!! 감사합니다😊

2024-10-17 11:10 UTC, Hyobeen-Park commented on app/src/main/java/org/sopt/and/feature/signup/SignUpViewModel.kt
> +        }
value 값을 그대로 변경하게 되면 다른 스레드에서 동시에 값을 수정하려고 할 때 문제가 발생할 수 있지만 update를 사용하면 원자성이 보장됩니다!

2024-10-17 11:17 UTC, Hyobeen-Park commented on app/src/main/java/org/sopt/and/feature/signup/SignUpViewModel.kt
> +    }
그렇다면 count를 통해 `Boolean `값을 반환하기보다는 `state`를 반환하는 방법으로 구현할 것 같습니다! 조건을 충족하지 못했다면 `invalidUpperCase `이런 느낌으로 충족하지 못한 조건을 알려줄 것 같네요!

2024-10-17 11:17 UTC, Hyobeen-Park commented on app/src/main/java/org/sopt/and/feature/signup/SignUpViewModel.kt
> +
헉!! 알려주셔서 감사합니다😅

2024-10-17 11:38 UTC, Hyobeen-Park commented on app/src/main/java/org/sopt/and/feature/signup/SignUpScreen.kt
> +    val signUpState by viewModel.signUpState.collectAsState()
앗하! 감사합니다!!

2024-10-17 11:48 UTC, Hyobeen-Park commented on app/src/main/java/org/sopt/and/feature/signup/SignUpScreen.kt
> +    val password = remember { mutableStateOf("") }
우왕 조언 감사합니다..!! 말씀하신대로 상태관리를 viewModel과 Screen에서 동시에 하고 있었네요!! 다시 한번 현재 관리중인 상태들을 정리해보는 것이 필요할 것 같아요 감사합니다😊

2024-10-17 11:50 UTC, Hyobeen-Park commented on app/src/main/java/org/sopt/and/feature/signup/SignUpScreen.kt
> +            onPasswordChange = TODO()
파라미터가 있을 때 (_, _ -> ) 이렇게 할 수 있는건 처음 알았어요..!! 오호.... 확실히 제가 보기에도 아래 방식대로 하는 것이 더 좋을 것 같네요 감사합니다!!

2024-10-17 11:56 UTC, Hyobeen-Park commented on app/src/main/java/org/sopt/and/feature/signin/SignInActivity.kt
> +        }
오!! SAA로 구현할 때는 `registerForActivityResult`를 어떻게 사용할 수 있을지 고민했었는데 `rememberLauncherForActivityResult`를 사용하면 되겠네요!! 알려주셔서 감사합니다😊

2024-10-17 12:03 UTC, Hyobeen-Park commented on app/src/main/java/org/sopt/and/feature/signin/SignInActivity.kt
> +    private var userPassword: String = ""
액티비티 재성성 시에는 해당 변수들은 ""로 초기화될 것 같네요... 테스트를 해볼 때는 액티비티가 재성성될 일이 딱히 없었어서 알아차리지 못했어요ㅎㅎ 안정적으로 기능을 구현하기 위해 해당 변수도 state로 받는 것이 좋을 것 같아요!

2024-10-17 12:07 UTC, Hyobeen-Park commented on app/src/main/java/org/sopt/and/feature/signin/SignInActivity.kt
> +    private fun isSignInAvailable(email: String, password: String): Boolean {
스낵바를 Activity에서 구현하면서 여기에 새로 추가해줬는데 뷰모델에 있는거를 삭제를 안했네요😅 생각해보니  뷰모델에서 로그인 여부를 확인하는 방식으로도 구현해보면 좋을 것 같아요!

2024-10-17 12:20 UTC, Hyobeen-Park commented on app/src/main/java/org/sopt/and/feature/signin/SignInScreen.kt
> +    viewModel: SignInViewModel = hiltViewModel(),
viewModel()은 viewModel()이 호출된 컴포넌트의 생명주기를 따르기 때문에 해당 컴포넌트가 종료되면 viewModel도 함께 소멸됩니다!

hiltViewModel()은 HiltViewModelFactory를 사용하는데 ViewModelStoreOwner가 NavBackStackEntry일 경우 HiltViewModelFactory를 통해 viewModel을 가져오고 그렇지 않으면 viewModel()과 동일하게 작동합니다

viewModel을 유지하며 화면 이동을 해야 할 때 hiltViewModel()을 사용하면 쉽게 viewModel을 유지할 수 있겠네요!!

2024-10-17 12:38 UTC, Hyobeen-Park commented on app/src/main/java/org/sopt/and/feature/mypage/component/MyPageTextButton.kt
> +fun MyPageTextButton(
오!! 애용하겠습니다

2024-10-17 12:40 UTC, Hyobeen-Park commented on app/src/main/java/org/sopt/and/feature/mypage/component/MyPageTextButton.kt
> +        Row {
오호 그럴 수 있겠네요!! alignment를 추가하는게 UI를 일정하게 보여줄 수 있을 것 같아요!

2024-10-17 12:42 UTC, Hyobeen-Park commented on app/src/main/java/org/sopt/and/core/designsystem/component/textfield/PasswordTextField.kt
> +    onValueChange: (String) -> Unit,
내부에서 onValueChange를 처리하고 콜백은 없앨 수 있도록 수정해보는 것이 좋겠네요!! 조언 감사합니다😊

2024-10-17 12:47 UTC, Hyobeen-Park commented on app/src/main/java/org/sopt/and/core/designsystem/component/SocialLoginButton.kt
> +            }
LazyRow에서는 key값을 통해 recomposition 여부를 결정합니다! key값을 따로 지정하지 않을 경우 자동으로 item의 index값으로 key값을 지정하게 되는데 이 경우 아이템의 일부가 변경되는 경우 key값도 변경되어 전체 리스트가 전부 recomposition이 일어나게 됩니다! 반면 직접 key값을 지정하면 아이템의 일부가 변경되어도 다른 아이템들의 key값은 그대로 유지되기 때문에 key값이 변경된 아이템들만 recomposition이 발생합니다

key라는 것을 최근에 알게 되었는데 아주 좋은 친구더라구요?!?? key값을 지정해주는 습관을 들이는 것이 성능 향상을 위해 좋을 것이라는 생각을 했습니다ㅎㅎ

2024-10-17 12:47 UTC, Hyobeen-Park commented on app/src/main/java/org/sopt/and/WavveApplication.kt
> +}
오 onCreate를 선언하지 않아도 괜찮군요!!

2024-10-17 12:55 UTC, Hyobeen-Park commented on app/src/main/AndroidManifest.xml
>              android:exported="true"
외부의 다른 앱에서 해당 액티비티로 접근 가능한지 여부를 `exported `로 지정합니다! true일 때는 다른 모든 앱에서 접근이 가능하고, false일 때는 특정 조건이 충족되는 경우를 제외하고는 접근이 불가합니다

추가적으로 알아보니 해당 속성을 명시적으로 지정하지 않을 경우 기기에 따라 서로 다른 기본값이 지정될 가능성이 존재하고 이로 인해 내부 구성요소가 공개되는 일이 발생할 수 있어 보안을 위해 `exported` 속성을 명시적으로 지정하는 것을 권장하고 있네요

https://developer.android.com/privacy-and-security/risks/android-exported?hl=ko

2024-10-17 12:57 UTC, Hyobeen-Park commented on app/src/main/java/org/sopt/and/core/designsystem/component/textfield/EmailextField.kt
> +            onValueChange(newValue)
넵!! 상태관리가 중복으로 이루어지면서 조금 꼬인 것 같네요😅 한번 수정해보겠습니다!

2024-10-17 12:58 UTC, Hyobeen-Park commented on app/src/main/java/org/sopt/and/core/designsystem/component/textfield/PasswordTextField.kt
BasicComponent를 만들어두는 것도 좋은 생각이네요!! 어떻게 하면 좋을지 고민해봐야겠어요ㅎㅎ

2024-10-23 12:12 UTC, MinseoSONG approved these changes

2024-10-23 12:15 UTC, merged