[FEAT] 3차 필수과제
AND-SOPT-ANDROID/hyobeen-park pull request #9
Opened 2024-11-01 14:14 UTC by Hyobeen-Park

## Related issue 🛠
- closed #8 

## Work Description ✏️
- 컴포넌트화하기

## Screenshot 📸

https://github.com/user-attachments/assets/e662f6a6-999d-45a9-b75e-9023d041acc5

## Uncompleted Tasks 😅
- 없습니당!

## To Reviewers 📢

2024-11-03 09:44 UTC, beom84 approved these changes
3차과제도 고생하셨습니다!!!

2024-11-03 09:44 UTC, beom84 commented on app/src/main/java/org/sopt/and/core/designsystem/component/image/WavveAsynkImge.kt
이 컴포넌트 하나로 가독성이 정말 많이 좋아졌네요!!!

2024-11-03 11:59 UTC, wjdrjs00 approved these changes
3주차도 고생많으셨습니다!

2024-11-03 11:59 UTC, wjdrjs00 commented on app/src/main/java/org/sopt/and/core/designsystem/component/image/WavveAsynkImge.kt
컴포넌트 하나 잘만들면 코드가 확실히 줄어드네요!

2024-11-03 14:55 UTC, MinseoSONG commented on app/src/main/java/org/sopt/and/core/designsystem/component/image/WavveAsynkImge.kt
> +}
자주 사용하는 AsyncImage 형식을 컴포넌트화하기 .. ! 확실히 코드 길이도 줄이고 가독성이 좋아지겠어용

2024-11-03 14:55 UTC, MinseoSONG commented on app/src/main/java/org/sopt/and/feature/home/HomeRoute.kt
> +                            cornerRadius = 5.dp,
8줄이 3줄이 되는 매직 🪄

2024-11-04 11:14 UTC, MinseoSONG approved these changes

2024-11-04 18:00 UTC, l2hyunwoo requested changes
한번 확인해주세요...그리고 효빈님께서 생각하시는 컴포넌트의 분리기준이라는것이 궁금합니다.

2024-11-04 18:00 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/and/core/designsystem/component/image/WavveAsynkImge.kt
> +        contentDescription = "",
contentDescription에 무조건 empty string이 들어가는데(의도하신 것 같지만), 이후에는 관련있는 텍스트라도 추가할 수 있게 패러미터로 뚫어주시면 좋을 것 같습니다.

2024-11-04 18:00 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/and/feature/home/HomeRoute.kt
> +                            cornerRadius = 5.dp,
AsyncImage를 WavveAsyncImage로 한번 감싸주셨는데, 한번 더 wrapping한 이유가 있을까요?

2024-11-06 05:14 UTC, jihyunniiii reviewed
이번주에는 코드적인 수정 사항이 많이 없어서 UI 단 설계를 위주로 봐드리려고 하는데 노션이 접근이 되지를 않네요 ㅠㅠ 확인 부탁드립니다 ~

2024-11-13 04:16 UTC, Hyobeen-Park commented on app/src/main/java/org/sopt/and/core/designsystem/component/image/WavveAsynkImge.kt
> +        contentDescription = "",
파라미터로 받는게 확장성 측면에서 훨씬 더 좋을 것 같네요!! 감사합니다😊

2024-11-13 04:17 UTC, Hyobeen-Park commented on app/src/main/java/org/sopt/and/feature/home/HomeRoute.kt
> +                            cornerRadius = 5.dp,
AsyncImage를 여러 번 사용하고 있는데 더 쉽게 사용할 수 있는 형태로 만들면 좋을 것 같아서 WavveAsyncImage로 만들게 되었습니다..!!

2024-11-13 04:23 UTC, merged